apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      version: 2.8.2
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: cattle-system
  valuesFiles:
    - ./rancher-values.yaml

