apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      version: 2.11.3        # or leave blank for latest
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: cattle-system
  values:
    hostname: 192.168.10.36.sslip.io
    replicas: 1
  valuesFrom:
    - kind: Secret
      name: bootstrap-password
      valuesKey: bootstrapPassword
      targetPath: bootstrapPassword
