apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  releaseName: tailscale-operator
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      version: "*"
  interval: 5m
  install:
    createNamespace: true
  valuesFrom:
    - kind: Secret
      name: tailscale-oauth
      valuesKey: oauth.clientId
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-oauth
      valuesKey: oauth.clientSecret
      targetPath: oauth.clientSecret

