apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-pvc
  namespace: audiobookshelf
  labels:
    type: longhorn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
