apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:/MWRkEraKyFlkd667+ELxZqG4RdL7DmH2vs5vHEfAzhnxs1ueC5AYAlyK7fVxTwJKRaOY1iat0000Z/4gZaYBeEbA59ehd9qxDwbevHIEgCwnCeUTbv3ijvrscBu3gOzFmEKEXxFsDtWUHLtWSfzcKlXzBXx/iXDgls61XINbppAhNyZoQIVUel5P9YkD54IvfkMFrfjlxjpn8JOP2FYgqsbOTmDTO4bhiq4L+Ay4rLvlzjAh3D7eppnBeKUfkyPBhFagWz/ujhjcZAIbFBkRWGWtfToCeTxCiifAl0zqVNzEQ9ogyRgSc431abu4ZdOxAiehkdolDWOyvkUstMS0+j3yDs=,iv:Z9bP9xNFzbbSojwmL9aaD3+/VZOO9VQHSxArRJIXD30=,tag:p0FxTrLOmCuNu2+hLovN5g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1da0xdujr5nskquwzpazsa4v7u5qv9a8vrttpue75apphqu9urfys85ad5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMXAyWnM1TjI0MGdCZVli
            YjVWYTlveG1lbEtXVUg0ejRSNHN1Y0psa1ZFCnN3b0JEeGloRnZQOFU1eVF0RS9J
            MFhOTWNka255dGN4WU9Ja250SzFtaG8KLS0tIHNLNmVrUXg2ekhQZHJROWlWVnZT
            S0lLdXBDZ2JRdDAyRDE2b2J6cWJ2aTQK5bE66vzvH1Oy/dXGKkA3Hv3KyU51YRjJ
            JkWoBvD9AgGp0vbEk2f7Mpd4UaLHqQWj5RKGwTAtkpikRJbh7XC2yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T03:53:35Z"
    mac: ENC[AES256_GCM,data:OGsYcDaGrD8HfAqZD1w454IwqKtS46y28heDT+v3eSOKj2V9VXCawV/u9bK6itwq0UX0TIi+sVMepQ3Y6i9RhtWWIwf/20Nf1XazqJdMF0xAEMdTKzi29J1+NgjfS6/lUtY0xisaPo/SipB2umcnbLPdti05Ow9xp+SiKmPfLd0=,iv:/5fzD/XSvLK3juehmDwRnWkcfmr1+jeZCFShKV5eKXY=,tag:7R9GsEWuU9af3eKV3kAkVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
