apiVersion: v1
data:
    password: ENC[AES256_GCM,data:OVynuWLRPQjt9b17NOAcN8Eflu5EYG3AerZnicgwQTnEBvXaoQDPwZp8vYLgkUwXywQCX8APfTkwBlXP6ctXKA==,iv:JZDTNk/7+OwRfrBUe+j98AL3AdoTR8orODE2G9nbwOA=,tag:lEmualPtEjRLjnls8Sgelg==,type:str]
    user: ENC[AES256_GCM,data:xTtUPaxItr4=,iv:F7vnIShMqpdOwvqxmbwnAhTmUssQ1+5CDKrxPjinNwk=,tag:HJJ6rrjyEBQXJq7QzNc9pw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kj-secret
sops:
    age:
        - recipient: age1da0xdujr5nskquwzpazsa4v7u5qv9a8vrttpue75apphqu9urfys85ad5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTVhWU0d4NkxnZXpTQWF3
            VDBORzMzb2pSeGdRMk9ZVzFBcUJKZmdzc1RZCndiM25RUi9BeWNIRytEUkVoMUxo
            eXpicnFZZkFYdWVhMy8xV1M5RkhyOWMKLS0tIHFiRVYrUTZRbnZNU3lUd2p0T2VO
            NGtGNGRxbGdmNW4rZzBEYlRtQlFxOUkKXe7VVe03YKDEUUvSXP0bC9ZzTLxz9gQW
            cBT27sdvj7NXAG0pi4XhgKs0PKttXNXTL4lda+mahd34UjeD7aGtug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T16:43:14Z"
    mac: ENC[AES256_GCM,data:WBRowFo5U9RP2XUulG5pyjBOP1kL1/fucRLlD6W7M5zFkJuI6JxY1ARm/hy5/Iskqm0IsKnNs64q+3WjwiLgpHIZ/8SZIDttD+iKRhPTLdM3ZBk9dz26MfwA1v452zhVfI3DGs50PeuRNWx+ORBx7Udyqnii8r4cfCj6l4jCkB4=,iv:Um2e2bqoc6Yo6LtU+DsbZQleVm8a9mRCXuzqmrc6DgQ=,tag:080GzOymVjes6ol0Z8Ng2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
