apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:AIcdRKg/as6UFScU95KnycIaGAtYgDn/6aPt7UdB0inugiXn9FUnSE/0iszlebu/P5kuQPPQkqA=,iv:5tR8wlyBLoYmsooUacxSnOAKtNfF3stfnhpZ3vEcoeU=,tag:RCZch0IBsy3mODNbZ3AeRg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
    namespace: renovate
sops:
    age:
        - recipient: age1da0xdujr5nskquwzpazsa4v7u5qv9a8vrttpue75apphqu9urfys85ad5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcWlHOFFnNkhDS2RsQU9x
            T0hFTW1jQlVtNTRlK1hPcU9sY2FXZVI5bEJNCjhPc1B1Q3M0K2tjdDVFcGdVdTZl
            SC8wWFpkc2lha2NHQlBrdWpVL2R0K2sKLS0tIEozeXdVN2VrREswdjZmTlE2MTFL
            QzFuQkJNNDlrMGxGV1lPMnhpUXZZeEkK0fYbXYPPVWsHeUao2zEmuOP89BkNJmy8
            KeaFUe938bkN0wFrF8+ZoXm6rM59OvyM2AvMpo0rmSx8p10fe86Z8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-23T00:55:57Z"
    mac: ENC[AES256_GCM,data:7dueYo3ovngt5VcDE61Jr/Q7ICN858RKBk4xKA6VKCEc3eQsn80Z58rWy8WWFDlwMXmm2xmbOwpqWrKQHDDKwDnzVzSCswfdx1fE3YjfqHNrg5yu4MqGF3HsMUN1CvaSn2/z+WI9cFRvaHmOe4vRyEcpyplphW67Q2tPOGKsomw=,iv:sy6bjoZ9gA5Qspt/er1eKGZnWo9xcZhhOsksA63ZLFo=,tag:K/3jZ/5NpBchFT9GLVJIdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
