apiVersion: v1
kind: Service
metadata:
  labels:
    app: linkding
  name: linkding-cftunnel
  namespace: linkding
spec:
  ports:
  - port: 9090
    protocol: TCP
  selector:
    app: linkding
  type: ClusterIP
