apiVersion: v1
kind: Service
metadata:
  labels:
    app: linkding
  name: linkding-loadbalancer
  namespace: linkding
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: linkding
    # app.kubernetes.io/instance: prometheus-stack
    # app.kubernetes.io/name: grafana
  type: LoadBalancer
