apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-ha-pvc
  namespace: linkding
  labels:
    type: longhorn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
